import Head from "next/head";
import Link from "next/link";
import Script from "next/script";

export default function Home() {
  return (
    <div className=""> 
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      </div>
      <div className="bg-white pb-5 pt-2">
      <div className="ml-auto mr-auto mt-12 items-center text-center max-w-[500px] lg:max-w-[650px] space-y-3">
        <p className="text-blue-900 text-sm font-medium text-center">ONLINE RESUME BUILDER</p>
        <div className="text-2xl text-gray-900 font-extrabold lg:text-4xl">Only 2% of resumes make it past the first round. Be in the top 2%</div>
        <p className="text-gray-900 text-md lg:text-xl">Use professional field-tested resume templates that follow the exact ‘resume rules’ employers look for. Easy to use and done within minutes - try now for free!</p>
        <Link href="/box/personal">
          <button className="bg-greenn-500 text-white text-lg xl:text-xl font-semibold rounded-md py-2 px-4 xl:py-4 xl:px-7 hover:bg-green-600">Create My Resume</button>
        </Link>
      </div>
      </div>
      
    </div>
  );
}
